name: CI

on: [push, pull_request, workflow_dispatch]

env:
  LIBRAW_GIT: https://github.com/LibRaw/LibRaw.git

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        libraw_ref: ['master']
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - run: git clone $LIBRAW_GIT -b ${{ matrix.libraw_ref }}
      name: Clone LibRaw

    - run: |
        env
        mkdir build
        cd build
        cmake --version
        cmake -DENABLE_OPENMP=OFF -DLIBRAW_PATH=$(pwd)/../LibRaw ..
        cmake --build .
      name: Build LibRaw
